In [1]:
# from typing import Sequence
import dask.array as da
# from dask_image.ndfilters import (
#     gaussian_filter,
#     gaussian_gradient_magnitude,
#     gaussian_laplace,
#     laplace,
# )

from ilastik.napari.filters import GaussianDask, FilterSet, GaussianGradientMagnitudeDask, LaplacianOfGaussianDask

features=FilterSet(filters=[GaussianDask(scale=0.3), GaussianGradientMagnitudeDask(scale=0.7), LaplacianOfGaussianDask(scale=0.3)]) # -> we use dask filters
print(features)

FilterSet(filters=[GaussianDask(scale=0.3),
                   GaussianGradientMagnitudeDask(scale=0.7),
                   LaplacianOfGaussianDask(scale=0.3)])


In [15]:
import numpy as np

# Define array size
shape = (20, 20)  # Example size of 20x20
array = np.zeros(shape, dtype=int)  # Initialize with zeros

# Define number and size of blobs
num_blobs = 5  # Number of blobs
blob_size = (3, 3)  # Blob dimensions (rows, cols)

for _ in range(num_blobs):
    # Randomly choose top-left corner of the blob
    row = np.random.randint(0, shape[0] - blob_size[0])
    col = np.random.randint(0, shape[1] - blob_size[1])
    
    # Randomly decide whether the blob contains 1s or 2s
    value = np.random.choice([1, 2])
    
    # Insert the blob
    array[row:row + blob_size[0], col:col + blob_size[1]] = value

print(array)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 2 2 2 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 2 2 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
import numpy as np
import dask
from sklearn.pipeline import Pipeline

from spatialdata import read_zarr

dask.config.set({'distributed.worker.daemon': False})

path = r"C:\Users\matti\Documents\WERK\STAGE\VIB\output" # change this

sdata = read_zarr(r"C:\Users\matti\Documents\WERK\STAGE\VIB\sdata_multi_channel.zarr\sdata_multi_channel.zarr")

#image=imread( "/Users/arnedf/VIB/DATA/test_data_ilastik/fov0/*.tiff" )

image=da.asarray(sdata[ "raw_image" ].data)
image

In [ ]:
from ilastik.napari.plugin import Dask_model


model = Dask_model(path)

labels = np.random.choice([0, 1, 2], size=image.shape[1:], p=[0.8, 0.1, 0.1])

In [ ]:
from matplotlib.pyplot import imshow

imshow( image[0] )  # we only plot the first channel

In [ ]:
import os
import joblib

def preprocessing_dask(image, estimators, preprocessing_path=None):
    pipe = Pipeline(estimators)

    arrays = []
    for i in image:
        arrays.append(pipe.transform(i))
    
    feature_map_lazy = da.concatenate(arrays, axis=2)
    print(feature_map_lazy)
    feature_map_lazy.to_zarr(
        preprocessing_path, "array.zarr", overwrite=True
    )  # this could be large
    joblib.dump(pipe, os.path.join(preprocessing_path, "preprocessing_pipe.pkl"))

estimators = [("features", features)]

preprocessing_path = path

preprocessing_dask(image, estimators=estimators, preprocessing_path = preprocessing_path )

In [ ]:
preprocessed_image=da.from_zarr( os.path.join( preprocessing_path, "array.zarr" ) )

preprocessed_image # preprocessed image

In [ ]:
# create some dummy annotations

labels = np.random.choice([0, 1, 2], size=image.shape[1:], p=[0.8, 0.1, 0.1])

In [ ]:
from dask.distributed import Client

from ilastik.napari.classifier import NDSparseDaskClassifier
from sklearn.ensemble import RandomForestClassifier

import loguru

logger = loguru.logger

def pixel_training_dask(X, labels, model_path=None, **client_kwargs):
    # WIP
    # load features from the zarr store
    clf = NDSparseDaskClassifier(RandomForestClassifier(n_jobs=-1))
    # add the classifier to the pipe, and then dump it

    client = Client(**client_kwargs)

    logger.info(f"Client dashboard link {client.dashboard_link}")

    with joblib.parallel_backend(
        "dask"
    ):  # note, NDSparseDaskClassifier with dask backend will still load data that was annotated in memory (although not the full dataset, only non-zero labels)
        clf.fit(X, labels)
    if model_path is not None:
        joblib.dump(clf, os.path.join(model_path))

# load features from the zarr store
image =  da.from_zarr(os.path.join( preprocessing_path, "array.zarr" ))
pixel_training_dask( X=image, labels=labels, model_path=os.path.join( path, "model.pkl" ), n_workers=1, threads_per_worker=10  )

In [ ]:
def pixel_classification_dask(
    image: da.Array | None,
    preprocessing_path,
    model_path,
    tmp_path,
    **client_kwargs,
):
    # WIP
    if image is None:
        # case where we train and run inference on same image
        image = da.from_zarr(preprocessing_path, "array.zarr")
    else:
        # load the preprocessing pipe from the path, do the preprocessing on image, and then do the classification
        # this should be used if we have a new image coming in, that we want to preprocesses and classify using pretrained model.
        preprocessing_pipe = joblib.load(preprocessing_path, "pipe.pkl")
        image = preprocessing_pipe.transform(image)
        # image could be large
        image.to_zarr(tmp_path)
        image = image.from_zarr(tmp_path)
    clf = joblib.load(model_path)
    client = Client(**client_kwargs)

    clf_scatter = client.scatter(
        clf
    )  # scatter the model otherwise issues with large task graph

    def _predict_clf(arr, model):
        arr = model.predict(arr)
        return arr.squeeze(-1)

    # probably need to use map_overlap instead of map_blocks here
    array_result = da.map_overlap(
        _predict_clf,
        image,
        dtype=image.dtype,
        drop_axis=-1,
        chunks=image.chunks[:-1],
        model=clf_scatter,
        # TODO output dtype not correct, need to fix via meta
    )

    return array_result

In [ ]:
results=pixel_classification_dask(image = None, preprocessing_path=path, model_path=os.path.join( path, "model.pkl" ), tmp_path = None,  n_workers=1, threads_per_worker=10)

In [ ]:
results # ->predicted labels

In [ ]:
imshow(results)

In [ ]:
da.from_zarr(
        preprocessing_path, "array.zarr", overwrite=True
    ) 